doctrine:
    dbal:
        driver: pdo_pgsql
        dbname: '%env(DB_NAME)%'
        host: '%env(DB_HOST)%'
        port: '%env(DB_PORT)%'
        user: '%env(DB_USER)%'
        password: '%env(DB_PASSWORD)%'

        types:
            invoice_items: App\Payments\Infrastructure\ORM\Type\InvoiceItemsType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Users:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Users/Infrastructure/ORM/Aggregate'
                prefix: 'App\Users\Domain\Aggregate'
                alias: Users
            Skills:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Skills/Infrastructure/Database/ORM/Aggregate'
                prefix: 'App\Skills\Domain\Aggregate'
                alias: Skills
            Testing:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Testing/Infrastructure/Database/ORM/Aggregate'
                prefix: 'App\Testing\Domain\Aggregate'
                alias: Testing
            Training:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Training/Infrastructure/ORM/Aggregate'
                prefix: 'App\Training\Domain\Aggregate'
                alias: Training
            Orders:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Orders/Infrastructure/ORM/Aggregate'
                prefix: 'App\Orders\Domain\Aggregate'
                alias: Orders
            Payment:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Payments/Infrastructure/ORM/Aggregate'
                prefix: 'App\Payments\Domain\Aggregate'
                alias: Payment
            Inventory:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Inventory/Infrastructure/ORM/Aggregate'
                prefix: 'App\Inventory\Domain\Aggregate'
                alias: Inventory
            Saga:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Saga'
                prefix: 'App\Saga'
                alias: Saga

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

#when@prod:
#    doctrine:
#        orm:
#            auto_generate_proxy_classes: false
#            query_cache_driver:
#                type: pool
#                pool: doctrine.system_cache_pool
#            result_cache_driver:
#                type: pool
#                pool: doctrine.result_cache_pool

#    framework:
#        cache:
#            pools:
#                doctrine.result_cache_pool:
#                    adapter: cache.app
#                doctrine.system_cache_pool:
#                    adapter: cache.system
