framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true

#
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            orders:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'App\Orders\Infrastructure\Event\EventEnvelopeSerializer'
                options:
                    exchange:
                        name: 'orders'
                        type: 'topic'
                    queues:
                        orders:
                            binding_keys:
                                - 'orders.#'
                                - 'payments.#'
            payments:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: 'App\Payments\Infrastructure\Event\EventEnvelopeSerializer'
                options:
                    exchange:
                        name: 'payments'
                        type: 'topic'
                    queues:
                        payments:
                            binding_keys:
                                - 'payments.#'
                                - 'orders.#'

        routing:
            'App\Orders\Infrastructure\Event\EventEnvelope': [orders, payments]
            'App\Payments\Infrastructure\Event\EventEnvelope': [orders, payments]
